on:
  push:


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: true

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: lilypichu.scss
          destination: main.css
          outputStyle: expanded
          indentWidth: 4

      - name: Add and Commit changes to main branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add *
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
